### ISSUE TITLE
Crashes on zone

### ISSUE THREAD

**Issue by GetAwayCoxn** [flanagak/Omen#1]
this addon will cause an exception violation in the addons plugin and crash every addon anytime you login/zone with this loaded

**Comment by flanagak** [comment]
need more details / data.
This is not crashing for myself and others.

Private Server or Retail?  (I have only tested on retail)
What version of Ashita 4 are you running?
What other plugins are loaded?
What zone change are you seeing the crash?  A specific zone or any zone change?

What is the text of the exception?

**Comment by flanagak** [comment]
Ok just got the exception as well....
Please disregard questions.

**Comment by flanagak** [comment]
Issue resolved in release v1.0.1
